language: cpp
os: osx

matrix:
  include:
    - osx_image: xcode12.2

    - osx_image: xcode8.3

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug && cmake --build . && ctest -C Debug --output-on-failure && mkdir ${HOME}/test-install && cmake --install . --prefix ${HOME}/test-install

